# Generated by Django 4.2.7 on 2024-01-18 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vcard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VcardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DisplayName', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=200)),
                ('Position', models.CharField(max_length=200)),
                ('PhoneNumber', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=50)),
                ('Website', models.CharField(max_length=50)),
                ('fileName', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
