# Generated by Django 4.2.7 on 2024-01-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0002_vcardinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcardinformation',
            name='UserID',
            field=models.IntegerField(),
        ),
    ]
