# Generated by Django 4.2.7 on 2024-01-20 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0003_alter_vcardinformation_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcardinformation',
            name='UserID',
        ),
    ]
