# Generated by Django 4.2.7 on 2024-01-20 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vcard', '0004_remove_vcardinformation_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcardinformation',
            name='UserID',
            field=models.ForeignKey(db_column='user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vcardinformation',
            name='Address',
            field=models.CharField(db_column='address', max_length=200),
        ),
        migrations.AlterField(
            model_name='vcardinformation',
            name='Company',
            field=models.CharField(db_column='company', max_length=200),
        ),
        migrations.AlterField(
            model_name='vcardinformation',
            name='DisplayName',
            field=models.CharField(db_column='display_name', max_length=200),
        ),
        migrations.AlterField(
            model_name='vcardinformation',
            name='Email',
            field=models.CharField(db_column='email', max_length=50),
        ),
        migrations.AlterField(
            model_name='vcardinformation',
            name='PhoneNumber',
            field=models.CharField(db_column='phone_number', max_length=12),
        ),
        migrations.AlterField(
            model_name='vcardinformation',
            name='Position',
            field=models.CharField(db_column='position', max_length=200),
        ),
        migrations.AlterField(
            model_name='vcardinformation',
            name='Website',
            field=models.CharField(db_column='website', max_length=50),
        ),
        migrations.AlterField(
            model_name='vcardinformation',
            name='active',
            field=models.BooleanField(db_column='active', default=True),
        ),
        migrations.AlterField(
            model_name='vcardinformation',
            name='fileName',
            field=models.CharField(db_column='file_name', max_length=100),
        ),
        migrations.AlterModelTable(
            name='vcardinformation',
            table='vcard_information',
        ),
    ]
