# Generated by Django 4.2.7 on 2024-01-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcard', '0005_vcardinformation_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcardinformation',
            name='logo',
            field=models.CharField(db_column='logo', default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vcardinformation',
            name='template',
            field=models.IntegerField(db_column='template', default=0),
            preserve_default=False,
        ),
    ]
